version: '2'

networks:
  default-network:
    driver: bridge

services:

  nginx:
    build:
      context: .
      dockerfile: deployment/local/docker/nginx/Dockerfile
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/var/www
    networks:
      - default-network

  php-fpm:
    build:
      context: .
      dockerfile: deployment/local/docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql_leader
      - redis
    container_name: private_file_storage_backend_php_fpm
    networks:
      - default-network

  mysql_leader:
    image: mysql:5.7
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    volumes:
      - ./deployment/local/mysql_leader/mysql.cnf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./persistent_data/mysql_leader:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=files
    networks:
      - default-network
    container_name: mysql_leader

  mysql_testing:
    image: mysql:5.7
    ports:
      - "${DOCKER_MYSQL_TESTING_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=files_testing
    networks:
      - default-network
    container_name: mysql_testing

  redis:
    image: redis:4.0
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    networks:
      - default-network
    container_name: redis

  phpmyadmin:
    depends_on:
      - mysql_leader
    image: phpmyadmin
    restart: always
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql_leader
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default-network
