swagger: "2.0"
info:
  title: File storage API
  description: Docs for file storage API
  version: 1.0.0
schemes:
  - http
host: 127.0.0.1:31080
basePath: /api

securityDefinitions:
  JWT:
    type: apiKey
    in: header
    name: Authorization

paths:

  /v1/auth:
    post:
      tags:
        - auth
      summary: Authorize user
      description: Authorize user via email and password
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          type: string
          name: X-Locale
          enum:
            - ru
            - en
        - name: LoginRequestBody
          in: body
          description: Login user request body
          required: true
          schema:
            $ref: "#/definitions/LoginRequestModel"
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/LoginSuccessResponseModel"
        403:
          description: Forbidden
          schema:
            $ref: "#/definitions/ForbiddenResponseModel"

  /v1/account/user:
    get:
      tags:
        - user
      summary: Get current user info
      description: Get info about user via authorization header
      security:
        - JWT: []
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: X-Locale
          enum:
            - ru
            - en
        - in: header
          name: Authorization
          required: true
          type: string
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/GetUserResponseModel"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"

definitions:

  # Login models

  LoginRequestModel:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
      password:
        type: string

  LoginSuccessResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string
      token:
        type: string

  # Get user model

  GetUserResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string
      user:
        $ref: "#/definitions/UserResponseModel"

  # Common models

  UnauthorizedResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string

  ForbiddenResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string

  UserResponseModel:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      name:
        type: string
      roles:
        type: array
        items:
          $ref: "#/definitions/RoleResponseModel"

  RoleResponseModel:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      systemName:
        type: string
