swagger: "2.0"
info:
  title: File storage API
  description: Docs for file storage API
  version: 1.0.0
schemes:
  - http
host: 127.0.0.1:31080
basePath: /api

securityDefinitions:
  JWT:
    type: apiKey
    in: header
    name: Authorization

paths:

  /v1/auth:
    post:
      tags:
        - auth
      summary: Authorize user
      description: Authorize user via email and password
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          type: string
          name: X-Locale
          enum:
            - ru
            - en
        - name: LoginRequestBody
          in: body
          description: Login user request body
          required: true
          schema:
            $ref: "#/definitions/LoginRequestModel"
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/LoginSuccessResponseModel"
        403:
          description: Forbidden
          schema:
            $ref: "#/definitions/ForbiddenResponseModel"
        422:
          description: Validation failed
          schema:
            $ref: "#/definitions/ValidationFailedResponseModel"

  /v1/account/user:
    get:
      tags:
        - user
      summary: Get current user info
      description: Get info about user via authorization header
      security:
        - JWT: []
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: X-Locale
          enum:
            - ru
            - en
        - in: header
          name: Authorization
          required: true
          type: string
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/GetUserResponseModel"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
    put:
      tags:
        - user
      summary: Update current user info
      description: Update current user info partialy
      security:
        - JWT: [ ]
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          type: string
          name: X-Locale
          enum:
            - ru
            - en
        - in: header
          name: Authorization
          required: true
          type: string
        - name: UpdateUserRequestBody
          in: body
          description: Update user request body
          required: true
          schema:
            $ref: "#/definitions/UpdateUserRequestModel"
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/SimpleSuccessResponseModel"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        422:
          description: Validation failed
          schema:
            $ref: "#/definitions/ValidationFailedResponseModel"

  /v1/account/files:
    post:
      tags:
        - file
      summary: Create file
      description: Create file for current user
      security:
        - JWT: [ ]
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          type: string
          name: X-Locale
          enum:
            - ru
            - en
        - in: header
          name: Authorization
          required: true
          type: string
        - name: CreateUserFileRequestBody
          in: body
          description: Create user file request body
          required: true
          schema:
            $ref: "#/definitions/CreateUserFileRequestModel"
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/SimpleSuccessResponseModel"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        403:
          description: Forbidden
          schema:
            $ref: "#/definitions/ForbiddenResponseModel"
        422:
          description: Validation failed
          schema:
            $ref: "#/definitions/ValidationFailedResponseModel"

  /v1/account/files/{file}:
    delete:
      tags:
        - file
      summary: Delete file
      description: Delete specific file for current user
      security:
        - JWT: [ ]
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: X-Locale
          enum:
            - ru
            - en
        - in: header
          name: Authorization
          required: true
          type: string
        - in: path
          name: file
          required: true
          type: number
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/SimpleSuccessResponseModel"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        403:
          description: Forbidden
          schema:
            $ref: "#/definitions/ForbiddenResponseModel"
        404:
          description: Not found
          schema:
            $ref: "#/definitions/NotFoundResponseModel"

  /v1/admin/invitations:
    post:
      tags:
        - invitation
      summary: Create invitation for user
      description: Create invitation for user via email
      security:
        - JWT: [ ]
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          type: string
          name: X-Locale
          enum:
            - ru
            - en
        - in: header
          name: Authorization
          required: true
          type: string
        - name: InviteUserRequestBody
          in: body
          description: Invite user request body
          required: true
          schema:
            $ref: "#/definitions/InviteUserRequestModel"
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/SimpleSuccessResponseModel"
        401:
          description: Unauthorized
          schema:
            $ref: "#/definitions/UnauthorizedResponseModel"
        403:
          description: Forbidden
          schema:
            $ref: "#/definitions/ForbiddenResponseModel"
        422:
          description: Validation failed
          schema:
            $ref: "#/definitions/ValidationFailedResponseModel"

  /v1/invitations/confirm:
    get:
      tags:
        - invitation
      summary: Confirm invitation
      description: Confirm specific invitation by code
      parameters:
        - in: query
          name: code
          required: true
          type: string
      responses:
        301:
          description: Redirect to login or error page

definitions:

  # Login models

  LoginRequestModel:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
      password:
        type: string

  LoginSuccessResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string
      token:
        type: string

  # Get user model

  GetUserResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string
      user:
        $ref: "#/definitions/UserResponseModel"

  # Update user model

  UpdateUserRequestModel:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      password:
        type: string

  # Create file model

  CreateUserFileRequestModel:
    type: object
    required:
      - file
    properties:
      file:
        $ref: "#/definitions/CreateFileRequestModel"
      description:
        type: string

  # Admin / Invite user model

  InviteUserRequestModel:
    type: object
    required:
      - email
      - expiredAt
    properties:
      email:
        type: string
      password:
        type: string
      name:
        type: string
      expiredAt:
        type: string

  # Common models

  SimpleSuccessResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string

  UnauthorizedResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string

  ForbiddenResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string

  NotFoundResponseModel:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string

  ValidationFailedResponseModel:
    type: object
    properties:
      errors:
        type: object

  UserResponseModel:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      name:
        type: string
      roles:
        type: array
        items:
          $ref: "#/definitions/RoleResponseModel"

  RoleResponseModel:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      systemName:
        type: string

  CreateFileRequestModel:
    type: object
    required:
      - name
      - mime
      - content
    properties:
      name:
        type: string
      mime:
        type: string
      content:
        type: string
